### PR TITLE
Convert docs to MyST

### PR DESCRIPTION
**Pull request by jtpio**
This should make authoring docs easier with Markdown.

- [x] Add / update the documentation

### CODE REVIEW

**Comment by pierrepo** [comment]
I :heart: this idea

**Comment by jtpio** [comment]
This looks good locally and CI is passing.

Not sure why the ReadTheDocs PR preview is not showing up here, although it should be enabled (https://github.com/plasmabio/plasma/issues/201).

**Review by pierrepo — COMMENTED** [review]
Looks good. Thanks @jtpio 

I let you merge.

**Comment by jtpio** [comment]
OK thanks @pierrepo for the review.

Let me know if you notice any issue when the latest docs are built.

**Comment by jtpio** [comment]
> Not sure why the ReadTheDocs PR preview is not showing up here, although it should be enabled (#201).

Ah so for references the docs seem to be built: https://plasmabio--203.org.readthedocs.build/en/203/overview/index.html

But the check doesn't show in the list of GitHub checks.

**Pull request merged**
