### PR TITLE
Update to the new `repo2docker` image

### LINKED ISSUE #190: Update repo2docker docker image
Running the `tljh.yml` playbook does not the update the repo2docker Docker image.
For that, the `force_source: True` parameter is needed in the corresponding rule:
```
    # Pull the repo2docker image to build user images
    - name: Pull jupyter/repo2docker
      docker_image:
        name: jupyter/repo2docker
        tag: master
        source: pull
        force_source: True
```

Doing that, running the playbook indeed updates the repo2docker image. It also keeps the former image that may or may not expected.

Unfortunately, building environments with this new repo2docker image is failing...

### PR DESCRIPTION
**Pull request by jtpio**
Fixes #190

## Changes

- [x] Pull from `quay.io/jupyterhub/repo2docker`
- [x] Pin to `jupyterhub~=1.5` for now
- [x] Update to `dockerspawner~=12.1`
- [x] Fix awaitable check introduced in a recent (1.3?) jupyterhub release  
- [x] Update docs build
- [x] Update to newer Python versions on CI

### CODE REVIEW

**Comment by jtpio** [comment]
The docs are correctly built for this PR: https://plasmabio--193.org.readthedocs.build/en/193/index.html

But now showing as a GitHub check...

**Comment by pierrepo** [comment]
Do you believe this PR is ready to be merged?

**Comment by jtpio** [comment]
Yes I think so.

Will do a quick check on a new instance and follow-up with PRs if needed.

**Comment by jtpio** [comment]
Looking good after a quick smoke test on a new VM:

image

image

**Comment by pierrepo** [comment]
Awesome!

**Pull request merged**
