### PR TITLE
Rename to Plasma

### LINKED ISSUE #154: Rename to plasma
To keep it consistent between:

- this repository
- the TLJH plugin
- the documentation
- the twitter account

We can rename and use the name "plasma" to refer to the project itself, instead of "plasmabio":

- [x] the repo becomes: https://github.com/plasmabio/plasma
- [x] the TLJH plugin becomes: `tljh-plasma`
- [x] mentions to "PlasmaBio" in the docs become: "Plasma" (or "PLASMA"?) 
- [x] rename in LICENSE: https://github.com/plasmabio/plasma/blob/b1c8e6d26da368790fe7d8fc04469fe758020587/LICENSE#L3
- [x] update README in https://github.com/plasmabio/tljh-repo2docker: https://github.com/plasmabio/tljh-repo2docker/pull/17
- [x] update readthedocs to https://plasma.readthedocs.io

### PR DESCRIPTION
**Pull request by jtpio**
Fixes #154.

- [x] Add / update the documentation

### CODE REVIEW

**Comment by jtpio** [comment]
cc @pierrepo if you want to proof-read this

**Comment by jtpio** [comment]
We need to keep https://plasmabio.readthedocs.io as the base readthedocs URL since https://plasma.readthedocs.io is taken.

**Comment by pierrepo** [comment]
Thanks @jtpio 
Could you update the README and rename `tljh-plasmabio` directory?

**Comment by jtpio** [comment]
That should be part of the changes for this PR.

We can press the merge button if it looks good.

**Comment by pierrepo** [comment]
OK Sorry.

**Pull request merged**
