### PR TITLE
Print mounted disk from Ansible task, make home dir configurable

### LINKED ISSUE #138: Create ansible task to get device name for quota
As specified in the doc, one has to run the following command on the host to get device name:
```
cat /etc/fstab
```
To stay in line with the current strategy to handle hosts, one could use ansible instead.

An ad-hoc command could be:
```
$ ansible -i hosts -u ubuntu -m command -a "cat /etc/fstab" -o
``` 
But for some reason, this command does not work...

Another alternative could be to create dedicated task in the playbook `quotas.yml`:
```
    - name: List mounted devices on hosts
      shell: cat /etc/fstab
      register: fstab
      tags:
        - run
        - discover
    
    - name: Print mounted devices on hosts
      debug: var="fstab.stdout_lines + [ fstab.stderr ]"
      tags:
        - run
        - discover
```
The `dicover` tag could be use to select tasks. The `never` tag prevents tasks to run by default.
```
$ ansible-playbook -i hosts -u ubuntu quotas.yml --tags "discover"

PLAY [all] *************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************
ok: [51.68.113.239]

TASK [List mounted devices on hosts] ***********************************************************************************************************
changed: [51.68.113.239]

TASK [Print mounted devices on hosts] **********************************************************************************************************
ok: [51.68.113.239] => {
    "fstab.stdout_lines + [ fstab.stderr ]": [
        "LABEL=cloudimg-rootfs / ext4 usrquota,grpquota 0 0",
        "LABEL=UEFI\t/boot/efi\tvfat\tdefaults\t0 0",
        ""
    ]
}

PLAY RECAP *************************************************************************************************************************************
51.68.113.239              : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```
The output is not very nice looking but that should be sufficient.

### PR DESCRIPTION
**Pull request by pierrepo**
- Create ansible task to print out mounted disk on hosts
- Allow more flexibility for disk name and path on hosts
- Use 2 new Ansible variables

- [x] Add / update the documentation in the *Set Disk Quotas* section
- [x] Add / update the documentation in the *Deploying with Ansible* section (new `hosts` file format with variables)

This should fix #138

### CODE REVIEW

**Comment by pierrepo** [comment]
@jtpio this *should* be OK by now.
The scope of the PR slightly increased. Features are:

- There is an Ansible rule to query mounted devices on the server.
- Device name and path to apply quotas on are defined in the `hosts` file.
- User home dir can also be defined in the `hosts` file.

The documentation has been updated accordingly but I'm counting on your sharp eyes :eyes:

**Comment by jtpio** [comment]
Thanks :+1: 

We should check this will work with the `base_volume_path` defined in the plugin, used by the `SystemUserSpawner`:

https://github.com/plasmabio/plasma/blob/62a262313b90f86a610e398911b6eefa1aff6918/tljh-plasma/tljh_plasma/__init__.py#L22-L24

This might require adding a new field with `tljh-config`.

**Comment by pierrepo** [comment]
Thanks @jtpio 

>This might require adding a new field with tljh-config.

Could you have a look to it?

**Comment by jtpio** [comment]
Instead of adding a new variable with `tljh-config`, we can use the `pwd` module to get the user directory:

https://github.com/plasmabio/plasma/blob/809f505aebca34a24ad40198d21cf7a46b548bf6/tljh-plasma/tljh_plasma/__init__.py#L57

**Comment by pierrepo** [comment]
>  we can use the pwd module to get the user directory:

That is very clever. Does it mean Jupyter Hub will make its way even if users have different base home directory? For instance `/home/foo` for user `foo` and `/srv/home/bar` for user `bar`.

**Comment by jtpio** [comment]
Technically yes. Although it could be confusing to have home directories scattered on the disk.

**Comment by jtpio** [comment]
This branch can be tested by setting:

```yaml
tljh_plasma: git+https://github.com/plasmabio/plasma@create-ansible-task-to-get-device-name#"egg=tljh-plasma&subdirectory=tljh-plasma"
```

Here:

https://github.com/plasmabio/plasma/blob/2bdcfeecab80d760e9c87ff57ba9463231c50a28/ansible/vars/default.yml#L3

**Comment by pierrepo** [comment]
@jtpio It works nicely. Great job!
```
claire@plasmabio-pierrepo:~$ tree /srv
/srv
├── data
├── home
│   ├── claire
│   │   ├── test-bash
│   │   │   ├── LICENSE
│   │   │   ├── README.md
│   │   │   ├── binder
│   │   │   │   ├── apt.txt
│   │   │   │   ├── environment.yml
│   │   │   │   └── postBuild
│   │   │   └── example-notebook.ipynb
│   │   └── test-python
│   │       ├── LICENSE
│   │       ├── README.md
│   │       ├── environment.yml
│   │       ├── materials
│   │       │   └── example.ipynb
│   │       ├── postBuild
│   │       └── toto
│   ├── pierre
│   ├── sandrine
│   └── stu123
└── tljh-installer.py


```

**Pull request merged**
