### PR TITLE
Add a Permissions page to manage the access to user environments

### PR DESCRIPTION
**Pull request by jtpio**
Add a simple permission management page to assign unix groups to user environments (Docker images).

### TODO

- [x] Add an endpoint to manage user group permissions
- [x] Store the group <-> Docker image mapping in the JupyterHub database
- [x] Expose a UI to JupyterHub admins to manage permissions
- [x] Filter the list of groups so some of the default groups do not show up in the list (or make it configurable)
- [x] Add documentation
- [x] Add documentation for the excluded groups
- [x] Decide whether excluded groups should be set by default (in the `site.yml` with a predefined list of groups)
- [x] Decide on whether the permissions should be stored in the JupyterHub database or elsewhere
- [x] Add tests

mapping-group-docker-image-add-remove

### Previous UX (left here for reference)

mapping-group-docker-image

### CODE REVIEW

**Comment by pierrepo** [comment]
Hello @jtpio 
This seems awesome :+1: 
I thought we agreed to store the env / group relationship not in the JupyterHub database but in a external file (text based) instead. Do you feel keeping everything in the JupyterHub database is a better solution?

**Comment by pierrepo** [comment]
Oups, didn't see this point... :no_mouth: 
> [ ] Decide on whether the permissions should be stored in the JupyterHub database or elsewhere

**Comment by pierrepo** [comment]
One design question.
Would it more *natural* to list all envs and assign group to selected envs then the other way around?

**Comment by jtpio** [comment]
> I thought we agreed to store the env / group relationship not in the JupyterHub database but in a external file (text based) instead. Do you feel keeping everything in the JupyterHub database is a better solution?

It would indeed be nice to avoid databases as much as possible and stick to a single file :+1: 

Do you think a single json / yaml file somewhere on the disk would be more appropriate? We should also consider what the access patterns will be (a database handles concurrent access while it would not be guaranteed by opening and writing to a file directly) 

(another technical point is that the db is accessible from the handler which makes it convenient to use).

>  Would it more natural to list all envs and assign group to selected envs then the other way around?

It might yes. We should probably consider whether there will be more user groups, or more user environments to decide on the most intuitive UI. Having it the other way around could also simplify how the groups are filtered.

**Comment by jtpio** [comment]
Inverting groups and images selection, with the long list of (currently unfiltered) groups hidden behind a dropdown:

mapping-group-docker-image-inverted

**Comment by pierrepo** [comment]
This looks very nice @jtpio 
Here are a couple of ideas to (maybe) improve the UX:
- It's a good idea to keep a list of unwanted groups (usual Unix system groups) that would be hidden from the dropdown menu. We should have a way to keep track of those groups (yaml file ?)
- Is it possible to display under each env groups which access has already been granted?
image
- Could you rename the `Add Group` button to `Add/Remove group`?

**Comment by jtpio** [comment]
> It's a good idea to keep a list of unwanted groups (usual Unix system groups) that would be hidden from the dropdown menu. We should have a way to keep track of those groups (yaml file ?)

Maybe as a deployment / `tljh-config` option?

> Is it possible to display under each env groups which access has already been granted?

It should already be the case in the inline `Remove` button?

mapping-group-docker-image-add-remove

> Could you rename the `Add Group` button to `Add/Remove group`?

If the remove button is located next to the name of the group, then the button could stay `Add Group`?

**Comment by jtpio** [comment]
@pierrepo suggested to use an `include` list instead of `exclude` to manage the list of groups.

This sounds like a good idea and should simplify the configuration even more :+1: (no need to create a list of groups to exclude which depend on the Ubuntu installation).

Admins could then define their list of groups without worrying about existing ones. They could also version this list more easily.

Let's update this PR with this change.

**Comment by jtpio** [comment]
The last commits switch to using an `include` list instead of `exclude` so it's more coherent and intuitive.

We can iterate more in separate issues and PRs.

**Pull request merged**
