### PR TITLE
Add Ansible config file

### LINKED ISSUE #169: Add ansible.cfg file to better handle Ansible ouput
For instance:
```
# https://docs.ansible.com/ansible/latest/reference_appendices/config.html

[defaults]
# https://docs.ansible.com/ansible/latest/plugins/callback/profile_tasks.html
callback_whitelist = profile_tasks
# Use the YAML callback plugin.
stdout_callback = yaml
# Use the stdout_callback when running ad-hoc commands.
bin_ansible_callbacks = True
```

### PR DESCRIPTION
**Pull request by pierrepo**
Should fix #169 

This PR modifies all outputs from Ansible.
All command line screenshots will be updated later, once ongoing issues/PR are fixed/merged. One can create an extra issue as a reminder.

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks Pierre that looks good!

> All command line screenshots will be updated later, once ongoing issues/PR are fixed/merged. One can create an extra issue as a reminder.

Are there many of them? Or is it only the output on this page? https://docs.plasmabio.org/en/latest/install/ansible.html

**Comment by pierrepo** [comment]
>Are there many of them? Or is it only the output on this page? https://docs.plasmabio.org/en/latest/install/ansible.html

I guess only this one.

**Comment by jtpio** [comment]
Would it be possible to re-run `ansible-playbook site.yml -i hosts -u ubuntu` with the new config and paste the output in the docs?

**Comment by pierrepo** [comment]
Of course. Could please reset the VM? I'd like to take the opportunity to make a *screenshot* of a fresh install.

**Comment by pierrepo** [comment]
@jtpio Ansible doc has been updated. Thanks for the VM :clap:

**Comment by jtpio** [comment]
Looks good, thanks!

**Pull request merged**
